<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Aerio extends Model
{

    use HasFactory;
    protected $table="aerio";
    protected $fillable = [
       'nomeCompleto',
       'dataNascimento',
       'endereco',
       'telefone',
       'altura',
       'peso',
       'tam',
       'tamResponsavel',
       'imagem',
       'imagemResponsavel',
       'hospital',
       'setorLeito',
       'medicoCrm',
       'telefoneUnidade',
       'enderecoUnidade',
       'seis1',
       'qni61',
       'mr61',
       'seis2',
       'qni62',
       'despachante',
       'frotaHospital',
       'a63',
       'telefone63',
       'mReguladorEstadual',
       'sisreg',
       'dh',
       'bagagem',
       'hdaqt',
       'exameFisico',
       'apef',
       'exameLabor',
       'exameImagem',
       'prescM',
       'eca',
       'ssvv',
       'fr',
       'fc',
       'pa',
       'g',
       'temp',
       'hgt',
       'Modalidade',
       'sp02',
       'arAmbiente',
       'cateterto',
       'mascreservatorio',
       'vni',
       'iot',
       'peep',
       'voic',
       'pinsp',
       'ie',
       'obs5',
       'ecg',
       'mpc',
       'obsCirculatorio',
       'cc',
       'obscc',
       'hic',
       'obsHic',
       'isolamento',
       'respiratorio',
       'agenteEt',
       'antibiograma',
       'dieta',
       'acessoEV',
       'sondasDrenos',
       'drogasBic',
       'aerocinetose',
       'alergias3',
       'fobias3',
       'dpisiquiatra',
       'hospital4',
       'setorLeito4',
       'medicoResponsavel4',
       'telefone4',
        'endereco4',
        'qni4',
        'mr4',
        'qni42',
        'despachante4',
        'Sea4',
        'telefoneSea4',
        'ccfio',
        'cco2',
        'fioMaiorAl',
        'nomePrefixo',
        'tipoPista',
        'Hnoturna',
        'horarioDecolagem',
        'enderecoAo',
        'telefoneAo',
        'distanciaDP',
        'nomePrefixod',
        'tipoPistad',
        'Hnoturnad',
        'horarioDecolagemd',
        'enderecoAod',
        'telefoneAod',
        'distanciaDPd',
        'meteoro',
        'altOrigem',
        'altMaxima',
        'dmissao',
        'obsu1',
        'obsu2',
        'obsu3',
        'obsu4',
     
     ];
}


